apiVersion: v1
kind: Namespace
metadata:
  name: standard
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: standard
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=  # Base64-encoded value for "admin"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # Base64-encoded value for "password"
  POSTGRES_DB: c3RvcmVkYg==  # Base64-encoded value for "storedb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: standard
spec:
  # serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        # image: postgres:12.0-alpine
        image: postgres:14.5
        envFrom:
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 5432
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: standard
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: standard
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5Ab3B0Lm5j  # Base64-encoded value for "admin@opt.nc"
  PGADMIN_DEFAULT_PASSWORD: cm9vdA==  # Base64-encoded value for "root"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: standard
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        envFrom:
        - secretRef:
            name: pgadmin-secret
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
  namespace: standard
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30081
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: standard
  labels:
    app: fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: ghcr.io/tiamat-azure/fast-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: admin
        - name: DB_PWD
          value: password
        - name: DB_HOST
          value: postgres-svc
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: storedb
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
      initContainers:
      - name: init-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup postgres-svc.standard.svc.cluster.local; do echo waiting for service postgres-svc; sleep 2; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-svc
  namespace: standard
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: fastapi-ingress
#   namespace: standard
# spec:
#   rules:
#     - host:   # Remplacez par votre domaine ou laissez vide si vous n'avez pas de domaine
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: fastapi-svc
#                 port:
#                   number: 80
# ---